version: '3.8'

services:
    web:
        container_name: countingcarbs_backend
        image: countingcarbs-backend:1.0.0
        build:
            context: .
            dockerfile: Dockerfile
        command: npm run start
        ports:
            - "3001:3001"
            - "9229:9229"
        env_file:
            - .env
        networks:
            - nesjs-network
        volumes:
            - .:/usr/src/app
        restart: unless-stopped


networks:
    nesjs-network:
