import { ClimatiqRequest } from '../../domain/model/climatiq.model';

export const mapPlaidValuesToClimatiqBody = (
  categoryId: number,
  originalValue: number,
) => {
  let emissionFactor = {};
    switch (categoryId) {
        case 19025004: { emissionFactor = { activity_id: 'consumer_goods-type_alcoholic_drinks', }; break; }
        case 19047000: { emissionFactor = { activity_id: 'consumer_goods-type_tobacco_products', region: 'DE', }; break; }
        case 19025001: { emissionFactor = { activity_id: 'consumer_goods-type_food_beverage_stores', }; break; }
        case 19025002: { emissionFactor = { activity_id: 'consumer_goods-type_food_beverage_stores', }; break; }
        case 19025003: { emissionFactor = { activity_id: 'consumer_goods-type_food_beverage_stores', }; break; }
        case 13005053: { emissionFactor = { activity_id: 'consumer_goods-type_bread_other_baked_goods', }; break; }
        case 19046000: { emissionFactor = { activity_id: 'wholesale_trade-type_grocery_related_product_wholesalers', }; break; }
        case 13005000: { emissionFactor = { activity_id: 'restaurants_accommodation-type_na' }; break; }
        case 22012003: { emissionFactor = { activity_id: 'accommodation_type_hotel_stay', region: 'DE', }; break; }
        case 22012000: { emissionFactor = { activity_id: 'accommodation_type_holiday' }; break; }
        case 18068005: { emissionFactor = { activity_id: 'electricity-energy_source_electricity' }; break; }
        case 22009000: { emissionFactor = { activity_id: 'consumer_goods-type_gasoline_stations' }; break; }
        case 18069000: { emissionFactor = { activity_id: 'professional_services-type_veterinarians' }; break; }
        case 19012003: { emissionFactor = { activity_id: 'consumer_goods-type_footwear' }; break; }
        case 19012000: { emissionFactor = { activity_id: 'consumer_goods-type_clothing_clothing_accessories_stores' }; break; }
        case 18032000: { emissionFactor = { activity_id: 'consumer_goods-type_leather_leather_products', region: 'DE', }; break; }
        case 18045008: { emissionFactor = { activity_id: 'consumer_goods-type_dry_cleaning_laundry' }; break; }
        case 19022000: { emissionFactor = { activity_id: 'consumer_goods_rental-type_consumer_goods_general_rental_centers' }; break; }
        case 19053000: { emissionFactor = { activity_id: 'equipment_gardening_diy-type_building_material_garden_equipment_supplies_dealers' }; break; }
        case 18025000: { emissionFactor = { activity_id: 'domestic_services-type_private_households_with_employed_persons', region: 'DE', }; break; }
        case 18024025: { emissionFactor = { activity_id: 'consumer_goods-type_carpets_rugs' }; break; }
        case 18024018: { emissionFactor = { activity_id: 'consumer_goods-type_domestic_appliances_disposables' }; break; }
        case 18024001: { emissionFactor = { activity_id: 'consumer_goods-type_home_furniture_upholstered' }; break; }
        case 18024009: { emissionFactor = { activity_id: 'consumer_goods-type_paint_wallpaper_timber' }; break; }
        case 19027000: { emissionFactor = { activity_id: 'consumer_goods-type_furniture_other_manufactured_goods_not_elsewhere_specified', region: 'DE' }; break; }
        case 19037000: { emissionFactor = { activity_id: 'consumer_goods-type_musical_instruments' }; break; }
        case 18024014: { emissionFactor = { activity_id: 'electrical_equipment-type_home_cooking_appliances' }; break; }
        case 16002000: { emissionFactor = { activity_id: 'housing-type_imputed_rent' }; break; }
        case 18050010: { emissionFactor = { activity_id: 'housing-type_imputed_rent' }; break; }
        case 18024027: { emissionFactor = { activity_id: 'professional_services-type_architectural_engineering_related_services' }; break; }
        case 18068002: { emissionFactor = { activity_id: 'housing-type_water_waste_service_charges' }; break; }
        case 19000000: { emissionFactor = { activity_id: 'general_retail-type_all_other_retail' }; break; }
        case 19033000: { emissionFactor = { activity_id: 'consumer_goods-type_jewelry_silverware' }; break; }
        case 18045009: { emissionFactor = { activity_id: 'consumer_goods-type_salons_barber_shops' }; break; }
        case 18045000: { emissionFactor = { activity_id: 'consumer_services-type_hairdressing_beauty_treatment' }; break; }
        case 18044000: { emissionFactor = { activity_id: 'paper_products-type_paper' }; break; }
        case 19010000: { emissionFactor = { activity_id: 'paper_products-type_stationery' }; break; }
        case 19009000: { emissionFactor = { activity_id: 'consumer_goods-type_books' }; break; }
        case 17001018: { emissionFactor = { activity_id: 'consumer_goods-type_amusement_parks_arcades' }; break; }
        case 19008000: { emissionFactor = { activity_id: 'consumer_goods-type_boats_trailers_and_horses' }; break; }
        case 19038000: { emissionFactor = { activity_id: 'consumer_goods-type_books_newspapers_magazines_other_print_media' }; break; }
        case 19005003: { emissionFactor = { activity_id: 'consumer_goods-type_caravans_motorhomes' }; break; }
        case 19013001: { emissionFactor = { activity_id: 'consumer_goods-type_computer_software_games' }; break; }
        case 19041000: { emissionFactor = { activity_id: 'consumer_goods-type_pet_purchase_and_accessories' }; break; }
        case 19048000: { emissionFactor = { activity_id: 'consumer_goods-type_dolls_toys_games' }; break; }
        case 19007000: { emissionFactor = { activity_id: 'consumer_goods-type_equipment_for_sport_camping_open_air_recreation' }; break; }
        case 19045000: { emissionFactor = { activity_id: 'consumer_goods-type_equipment_for_sport_camping_open_air_recreation' }; break; }
        case 19021000: { emissionFactor = { activity_id: 'consumer_goods-type_electronics_purchase_repair_fees' }; break; }
        case 17001014: { emissionFactor = { activity_id: 'consumer_goods-type_gambling_establishments_except_casino_hotels' }; break; }
        case 19031000: { emissionFactor = { activity_id: 'consumer_goods-type_games_toys_and_hobbies' }; break; }
        case 17015000: { emissionFactor = { activity_id: 'consumer_goods-type_golf_courses_marinas_ski_resorts_fitness_other_rec_centers_industries' }; break; }
        case 17039000: { emissionFactor = { activity_id: 'consumer_goods-type_golf_courses_marinas_ski_resorts_fitness_other_rec_centers_industries' }; break; }
        case 17018000: { emissionFactor = { activity_id: 'consumer_goods-type_golf_courses_marinas_ski_resorts_fitness_other_rec_centers_industries' }; break; }
        case 17033000: { emissionFactor = { activity_id: 'consumer_goods-type_golf_courses_marinas_ski_resorts_fitness_other_rec_centers_industries' }; break; }
        case 17001009: { emissionFactor = { activity_id: 'consumer_goods-type_movies_film' }; break; }
        case 19036000: { emissionFactor = { activity_id: 'consumer_goods-type_movies_film' }; break; }
        case 17001008: { emissionFactor = { activity_id: 'consumer_goods-type_museums_historical_sites_zoos_parks' }; break; }
        case 17027000: { emissionFactor = { activity_id: 'consumer_goods-type_museums_historical_sites_zoos_parks' }; break; }
        case 17048000: { emissionFactor = { activity_id: 'consumer_goods-type_museums_historical_sites_zoos_parks' }; break; }
        case 17023002: { emissionFactor = { activity_id: 'consumer_goods-type_museums_historical_sites_zoos_parks' }; break; }
        case 17001011: { emissionFactor = { activity_id: 'consumer_goods-type_performances' }; break; }
        case 17002000: { emissionFactor = { activity_id: 'consumer_goods-type_sports' }; break; }
        case 17003000: { emissionFactor = { activity_id: 'consumer_goods-type_sports' }; break; }
        case 17004000: { emissionFactor = { activity_id: 'consumer_goods-type_sports' }; break; }
        case 17005000: { emissionFactor = { activity_id: 'consumer_goods-type_sports' }; break; }
        case 17008000: { emissionFactor = { activity_id: 'consumer_goods-type_sports' }; break; }
        case 17009000: { emissionFactor = { activity_id: 'consumer_goods-type_sports' }; break; }
        case 17010000: { emissionFactor = { activity_id: 'consumer_goods-type_sports' }; break; }
        case 17011000: { emissionFactor = { activity_id: 'consumer_goods-type_sports' }; break; }
        case 17012000: { emissionFactor = { activity_id: 'consumer_goods-type_sports' }; break; }
        case 17013000: { emissionFactor = { activity_id: 'consumer_goods-type_sports' }; break; }
        case 17014000: { emissionFactor = { activity_id: 'consumer_goods-type_sports' }; break; }
        case 17017000: { emissionFactor = { activity_id: 'consumer_goods-type_sports' }; break; }
        case 17019000: { emissionFactor = { activity_id: 'consumer_goods-type_sports' }; break; }
        case 17020000: { emissionFactor = { activity_id: 'consumer_goods-type_sports' }; break; }
        case 17026000: { emissionFactor = { activity_id: 'consumer_goods-type_sports' }; break; }
        case 17028000: { emissionFactor = { activity_id: 'consumer_goods-type_sports' }; break; }
        case 17029000: { emissionFactor = { activity_id: 'consumer_goods-type_sports' }; break; }
        case 17030000: { emissionFactor = { activity_id: 'consumer_goods-type_sports' }; break; }
        case 17031000: { emissionFactor = { activity_id: 'consumer_goods-type_sports' }; break; }
        case 17032000: { emissionFactor = { activity_id: 'consumer_goods-type_sports' }; break; }
        case 17034000: { emissionFactor = { activity_id: 'consumer_goods-type_sports' }; break; }
        case 17035000: { emissionFactor = { activity_id: 'consumer_goods-type_sports' }; break; }
        case 17036000: { emissionFactor = { activity_id: 'consumer_goods-type_sports' }; break; }
        case 17037000: { emissionFactor = { activity_id: 'consumer_goods-type_sports' }; break; }
        case 17038000: { emissionFactor = { activity_id: 'consumer_goods-type_sports' }; break; }
        case 17040000: { emissionFactor = { activity_id: 'consumer_goods-type_sports' }; break; }
        case 17042000: { emissionFactor = { activity_id: 'consumer_goods-type_sports' }; break; }
        case 17043000: { emissionFactor = { activity_id: 'consumer_goods-type_sports' }; break; }
        case 17044000: { emissionFactor = { activity_id: 'consumer_goods-type_sports' }; break; }
        case 17045000: { emissionFactor = { activity_id: 'consumer_goods-type_sports' }; break; }
        case 17046000: { emissionFactor = { activity_id: 'consumer_goods-type_sports' }; break; }
        case 17047000: { emissionFactor = { activity_id: 'consumer_goods-type_sports' }; break; }
        case 17001012: { emissionFactor = { activity_id: 'consumer_services-type_leisure_clubs_discos_social_gatherings' }; break; }
        case 17001006: { emissionFactor = { activity_id: 'consumer_services-type_leisure_clubs_discos_social_gatherings' }; break; }
        case 19043000: { emissionFactor = { activity_id: 'consumer_services-type_development_of_film_photos' }; break; }
        case 18064000: { emissionFactor = { activity_id: 'textiles-type_textiles', region: 'DE' }; break; }
        case 18059000: { emissionFactor = { activity_id: 'consumer_goods-type_software' }; break; }
        case 17022000: { emissionFactor = { activity_id: 'agriculture_fishing_forestry-type_agriculture_hunting_forestry_fishing' }; break; }
        case 18073000: { emissionFactor = { activity_id: 'agriculture_fishing_forestry-type_agriculture_hunting_forestry_fishing' }; break; }
        case 18073004: { emissionFactor = { activity_id: 'agriculture_forestry_support-type_agriculture_forestry_support'}; break; }
        case 18073003: { emissionFactor = { activity_id: 'livestock_farming-type_meat_animals_not_elsewhere_specified', region: 'DE' }; break; }
        case 19042000: { emissionFactor = { activity_id: 'health_care-type_pharmaceutical_products_pills_powders_solutions' }; break; }
        case 14001011: { emissionFactor = { activity_id: 'health_care-type_ambulances' }; break; }
        case 14001009: { emissionFactor = { activity_id: 'health_care-type_medicines_and_medical_products' }; break; }
        case 14001012: { emissionFactor = { activity_id: 'health_care-type_dentists' }; break; }
        case 14002000: { emissionFactor = { activity_id: 'health_care-type_physicians' }; break; }
        case 14001007: { emissionFactor = { activity_id: 'health_care-type_healthcare_practitioners_except_physicians_dentists' }; break; }
        case 14001010: { emissionFactor = { activity_id: 'health_care-type_hospitals' }; break; }
        case 14001013: { emissionFactor = { activity_id: 'health_care-type_residential_mental_retardation_mental_health_substance_abuse_other_facilities' }; break; }
        case 14001008: { emissionFactor = { activity_id: 'health_care-type_residential_mental_retardation_mental_health_substance_abuse_other_facilities' }; break; }
        case 12002001: { emissionFactor = { activity_id: 'health_care-type_nursing_community_care_facilities' }; break; }
        case 12002002: { emissionFactor = { activity_id: 'social_care-type_child_elderly' }; break; }
        case 12005000: { emissionFactor = { activity_id: 'social_care-type_child_day_care' }; break; }
        case 12017000: { emissionFactor = { activity_id: 'other_social_services-type_other_community_social_personal_services' }; break; }
        case 12008000: { emissionFactor = { activity_id: 'education-type_education_services', region: 'DE' }; break; }
        case 17007000: { emissionFactor = { activity_id: 'accommodation_type_hotels_campgrounds' }; break; }
        case 18013000: { emissionFactor = { activity_id: 'construction-type_na' }; break; }
        case 18037020: { emissionFactor = { activity_id: 'timber_forestry-type_products_of_wood_cork_straw_plaiting_materials', region: 'DE' }; break; }
        case 18053000: { emissionFactor = { activity_id: 'maintenance_repair-type_residential_maintenance_repair' }; break; }
        case 18050003: { emissionFactor = { activity_id: 'other_real_estate-type_real_estate_services', region: 'DE' }; break; }
        case 18050002: { emissionFactor = { activity_id: 'other_real_estate-type_real_estate_activities' }; break; }
        case 18050000: { emissionFactor = { activity_id: 'other_rental_estate-type_other_real_estate' }; break; }
        case 18068001: { emissionFactor = { activity_id: 'utilities-type_electricity_gas_water_supply' }; break; }
        case 18068004: { emissionFactor = { activity_id: 'utilities-type_electricity_gas_water_supply' }; break; }
        case 18061000: { emissionFactor = { activity_id: 'consumer_services-type_entertainment_cinema_events_tv_subscription' }; break; }
        case 17001009: { emissionFactor = { activity_id: 'consumer_services-type_entertainment_cinema_events_tv_subscription' }; break; }
        case 19029000: { emissionFactor = { activity_id: 'electrical_equipment-type_medical_precision_optical_instruments_watches_clocks', region: 'DE' }; break; }
        case 18051000: { emissionFactor = { activity_id: 'electrical_equipment-type_home_refrigerators_freezers' }; break; }
        case 19013002: { emissionFactor = { activity_id: 'electronics-type_telephones' }; break; }
        case 18029000: { emissionFactor = { activity_id: 'machinery-type_machinery_equipment_not_elsewhere_specified', region: 'DE' }; break; }
        case 18072000: { emissionFactor = { activity_id: 'machinery- type_welding_soldering_equipment_scales_balances_other_general_purpose_machinery' }; break; }
        case 19039000: { emissionFactor = { activity_id: 'office_equipment-type_office_supplies_not_paper' }; break; }
        case 12016000: { emissionFactor = { activity_id: 'communication_services-type_postal_services' }; break; }
        case 18008001: { emissionFactor = { activity_id: 'communication_services-type_internet_publishing_broadcasting' }; break; }
        case 18031000: { emissionFactor = { activity_id: 'communication_services-type_telephone_intenet_accounts_services' }; break; }
        case 12013000: { emissionFactor = { activity_id: 'communication_services-type_news_syndicates_libraries_archives_internet_publishing_all_other_information_services' }; break; }
        case 18063000: { emissionFactor = { activity_id: 'communication_services-type_post_telecommunication', region: 'DE' }; break; }
        case 10000000: { emissionFactor = { activity_id: 'financial_services-type_bank_fees' }; break; }
        case 18020007: { emissionFactor = { activity_id: 'financial_services- type_investment_advice_portfolio_management_other_financial_advising_services' }; break; }
        case 18020003: { emissionFactor = { activity_id: 'financial_services- type_investment_advice_portfolio_management_other_financial_advising_services' }; break; }
        case 18030000: { emissionFactor = { activity_id: 'insurance-type_na' }; break; }
        case 18048000: { emissionFactor = { activity_id: 'chemicals-type_plastics' }; break; }
        case 18055000: { emissionFactor = { activity_id: 'chemicals-type_synthetic_rubber_artificial_synthetic_fibers' }; break; }
        case 18037011: { emissionFactor = { activity_id: 'chemicals-type_other_non_metallic_mineral' }; break; }
        case 18037007: { emissionFactor = { activity_id: 'glass_products-type_glass_and_glass_products', region: 'DE' }; break; }
        case 18037010: { emissionFactor = { activity_id: 'metal_products-type_other_fabricated_metal_manufacturing' }; break; }
        case 18040001: { emissionFactor = { activity_id: 'mined_materials-type_lignite_brown_coal', region: 'DE' }; break; }
        case 18040002: { emissionFactor = { activity_id: 'mined_materials-type_other_nonferrous_metal_ores_concentrates', region: 'DE' }; break; }
        case 18040003: { emissionFactor = { activity_id: 'mined_materials-type_uranium_thorium_ores', region: 'DE' }; break; }
        case 18042000: { emissionFactor = { activity_id: 'mined_materials-type_mineral_oil_primary_material_production' }; break; }
        case 18037012: { emissionFactor = { activity_id: 'paper_and_cardboard-type_paper_primary_material_production'}; break; }
        case 18037014: { emissionFactor = { activity_id: 'plastics_rubber-type_rubber_plastic_products', region: 'DE' }; break; }
        case 18037015: { emissionFactor = { activity_id: 'plastics_rubber-type_rubber_plastic_products', region: 'DE' }; break; }
        case 18037000: { emissionFactor = { activity_id: 'manufacturing-type_manufacturing_not_classified_recycling' }; break; }
        case 12009000: { emissionFactor = { activity_id: 'organizational_activities-type_central_government' }; break; }
        case 18068003: { emissionFactor = { activity_id: 'homeworking_type_heating' }; break; }
        case 12018000: { emissionFactor = { activity_id: 'organizational_activities-type_religious_organizations' }; break; }
        case 12015003: { emissionFactor = { activity_id: 'organizational_activities-type_non_profit_institutions_serving_households' }; break; }
        case 12015000: { emissionFactor = { activity_id: 'organizational_activity-type_other_services_not_elsewhere_specified' }; break; }
        case 18020014: { emissionFactor = { activity_id: 'professional_services-type_accounting_tax_preparation_bookkeeping_payroll' }; break; }
        case 18001000: { emissionFactor = { activity_id: 'professional_services-type_advertising_public_relations' }; break; }
        case 18008000: { emissionFactor = { activity_id: 'professional_services-type_business_support' }; break; }
        case 18012000: { emissionFactor = { activity_id: 'professional_services-type_computer_related_services', region: 'DE' }; break; }
        case 18050007: { emissionFactor = { activity_id: 'professional_services-type_buildings_dwellings_services' }; break; }
        case 18036000: { emissionFactor = { activity_id: 'professional_services-type_management_consulting' }; break; }
        case 18012002: { emissionFactor = { activity_id: 'professional_services-type_custom_computer_programming' }; break; }
        case 18037003: { emissionFactor = { activity_id: 'professional_services-type_computer_systems_design' }; break; }
        case 18016000: { emissionFactor = { activity_id: 'professional_services-type_employment_services' }; break; }
        case 18007000: { emissionFactor = { activity_id: 'professional_services-type_environmental_other_technical_consulting_services' }; break; }
        case 18057000: { emissionFactor = { activity_id: 'professional_services-type_investigation_security' }; break; }
        case 18033000: { emissionFactor = { activity_id: 'professional_services-type_legal_services'}; break; }
        case 18001007: { emissionFactor = { activity_id: 'professional_services-type_marketing_research_all_other_miscellaneous_professional_scientific_technical_services' }; break; }
        case 18047000: { emissionFactor = { activity_id: 'professional_services-type_photographers' }; break; }
        case 18054000: { emissionFactor = { activity_id: 'professional_services-type_research_development_services', region: 'DE' }; break; }
        case 18056000: { emissionFactor = { activity_id: 'professional_services-type_scientific_research_development' }; break; }
        case 18074000: { emissionFactor = { activity_id: 'professional_services-type_specialized_design' }; break; }
        case 18071000: { emissionFactor = { activity_id: 'professional_services-type_specialized_design' }; break; }
        case 18065000: { emissionFactor = { activity_id: 'professional_services-type_travel_arrangement_reservation'}; break; }
        case 19052000: { emissionFactor = { activity_id: 'wholesale_trade-type_wholesale_trade_commission_trade_services_except_of_motor_vehicles_motorcycles' }; break; }
        case 19005000: { emissionFactor = { activity_id: 'wholesale_trade-type_motor_vehicle_motor_vehicle_parts_supplies' }; break; }
        case 18037013: { emissionFactor = { activity_id: 'wholesale_trade-type_petroleum_petroleum_products' }; break; }
        case 22001000: { emissionFactor = { activity_id: 'passenger_flight-route_type_na-aircraft_type_na-distance_na-class_na-rf_na' }; break; }
        case 22015000: { emissionFactor = { activity_id: 'transport_services-type_railway_transportation_services', region: 'DE' }; break; }
        case 22008000: { emissionFactor = { activity_id: 'passenger_ferry-route_type_na-fuel_source_na' }; break; }
        case 18010000: { emissionFactor = { activity_id: 'chemicals-type_compressed_gases' }; break; }
        case 19013000: { emissionFactor = { activity_id: 'wholesale_trade-type_wholesale_electronic_markets_agents_brokers' }; break; }
        case 18039000: { emissionFactor = { activity_id: 'metals-type_primary_material_production' }; break; }
        case 18040000: { emissionFactor = { activity_id: 'chemicals-type_chemical_fertilizer_minerals_salt_other_mining_quarrying_products_not_elsewhere_specified', region: 'DE' }; break; }
        default: { emissionFactor = "Na"; break;}
  }
  const parameterUnit = 'usd';
  const parameters = { money: originalValue, money_unit: parameterUnit };
  const climatiqBody = new ClimatiqRequest(parameters, emissionFactor);
  return climatiqBody;
};

export const mapGoogleValuesToClimatiqBody = (
    category: string,
    amount: number,
) => {
    let emissionFactor = {};
    switch (category) {
        case 'Train': { emissionFactor = { activity_id: 'passenger_train-route_type_local-fuel_source_electricity', region: 'DE' }; break; }
        case 'Car': { emissionFactor = { activity_id: 'passenger_vehicle-vehicle_type_car-fuel_source_bio_petrol-distance_na-engine_size_medium', region: 'DE' }; break; }
        case 'Bus': { emissionFactor = { activity_id: 'passenger_vehicle-vehicle_type_bus-fuel_source_na-distance_na-engine_size_na', region: 'DE' }; break; }
        case 'Subway': { emissionFactor = { activity_id: 'passenger_train-route_type_local-fuel_source_electricity', }; break; }
        case 'Tram': { emissionFactor = { activity_id: 'passenger_train-route_type_local-fuel_source_electricity', region: 'DE' }; break; }
        case 'Ferry': { emissionFactor = { activity_id: 'passenger_ferry-route_type_na-fuel_source_na', }; break; }
        case 'Vehicle': { emissionFactor = { activity_id: 'passenger_vehicle-vehicle_type_car-fuel_source_bio_petrol-distance_na-engine_size_medium', }; break; }
        default: { emissionFactor = "Na"; break; }
    }
    const parameterUnit = 'km';
    const parameters = { passengers: 1, distance: amount, distance_unit: parameterUnit };
    const climatiqBody = new ClimatiqRequest(parameters, emissionFactor);
    return climatiqBody;
};